2024-09-10 21:31:05,216 ERROR frappe Could not take error snapshot: 'NoneType' object has no attribute 'get'
Site: dcode.com
Form Dict: {}
Traceback (most recent call last):
  File "/home/ecosoft/frappe-bench/apps/frappe/frappe/app.py", line 99, in application
    init_request(request)
  File "/home/ecosoft/frappe-bench/apps/frappe/frappe/app.py", line 172, in init_request
    frappe.init(site=site, sites_path=_sites_path, force=True)
  File "/home/ecosoft/frappe-bench/apps/frappe/frappe/__init__.py", line 312, in init
    setup_module_map(include_all_apps=not (frappe.request or frappe.job or frappe.flags.in_migrate))
  File "/home/ecosoft/frappe-bench/apps/frappe/frappe/__init__.py", line 1746, in setup_module_map
    for module in get_module_list(app):
  File "/home/ecosoft/frappe-bench/apps/frappe/frappe/__init__.py", line 1594, in get_module_list
    return get_file_items(get_app_path(app_name, "modules.txt"))
  File "/home/ecosoft/frappe-bench/apps/frappe/frappe/__init__.py", line 1559, in get_app_path
    return get_pymodule_path(app_name, *joins)
  File "/home/ecosoft/frappe-bench/apps/frappe/frappe/__init__.py", line 1589, in get_pymodule_path
    return abspath(join(dirname(get_module(scrub(modulename)).__file__ or ""), *joins))
  File "/home/ecosoft/frappe-bench/apps/frappe/frappe/__init__.py", line 1530, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'erpnext'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ecosoft/frappe-bench/apps/frappe/frappe/utils/error.py", line 87, in log_error_snapshot
    log_error(title=str(exception), defer_insert=True)
  File "/home/ecosoft/frappe-bench/apps/frappe/frappe/utils/error.py", line 62, in log_error
    error_log = frappe.get_doc(
  File "/home/ecosoft/frappe-bench/apps/frappe/frappe/__init__.py", line 1387, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/ecosoft/frappe-bench/apps/frappe/frappe/model/document.py", line 85, in get_doc
    controller = get_controller(doctype)
  File "/home/ecosoft/frappe-bench/apps/frappe/frappe/model/base_document.py", line 67, in get_controller
    return import_controller(doctype)
  File "/home/ecosoft/frappe-bench/apps/frappe/frappe/model/base_document.py", line 91, in import_controller
    module = load_doctype_module(doctype, module_name)
  File "/home/ecosoft/frappe-bench/apps/frappe/frappe/modules/utils.py", line 247, in load_doctype_module
    app = get_module_app(module)
  File "/home/ecosoft/frappe-bench/apps/frappe/frappe/modules/utils.py", line 270, in get_module_app
    app = frappe.local.module_app.get(scrub(module))
AttributeError: 'NoneType' object has no attribute 'get'
2024-09-10 21:31:08,187 ERROR frappe Could not take error snapshot: 'NoneType' object has no attribute 'get'
Site: dcode.com
Form Dict: {}
Traceback (most recent call last):
  File "/home/ecosoft/frappe-bench/apps/frappe/frappe/app.py", line 99, in application
    init_request(request)
  File "/home/ecosoft/frappe-bench/apps/frappe/frappe/app.py", line 172, in init_request
    frappe.init(site=site, sites_path=_sites_path, force=True)
  File "/home/ecosoft/frappe-bench/apps/frappe/frappe/__init__.py", line 312, in init
    setup_module_map(include_all_apps=not (frappe.request or frappe.job or frappe.flags.in_migrate))
  File "/home/ecosoft/frappe-bench/apps/frappe/frappe/__init__.py", line 1746, in setup_module_map
    for module in get_module_list(app):
  File "/home/ecosoft/frappe-bench/apps/frappe/frappe/__init__.py", line 1594, in get_module_list
    return get_file_items(get_app_path(app_name, "modules.txt"))
  File "/home/ecosoft/frappe-bench/apps/frappe/frappe/__init__.py", line 1559, in get_app_path
    return get_pymodule_path(app_name, *joins)
  File "/home/ecosoft/frappe-bench/apps/frappe/frappe/__init__.py", line 1589, in get_pymodule_path
    return abspath(join(dirname(get_module(scrub(modulename)).__file__ or ""), *joins))
  File "/home/ecosoft/frappe-bench/apps/frappe/frappe/__init__.py", line 1530, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'erpnext'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ecosoft/frappe-bench/apps/frappe/frappe/utils/error.py", line 87, in log_error_snapshot
    log_error(title=str(exception), defer_insert=True)
  File "/home/ecosoft/frappe-bench/apps/frappe/frappe/utils/error.py", line 62, in log_error
    error_log = frappe.get_doc(
  File "/home/ecosoft/frappe-bench/apps/frappe/frappe/__init__.py", line 1387, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/ecosoft/frappe-bench/apps/frappe/frappe/model/document.py", line 85, in get_doc
    controller = get_controller(doctype)
  File "/home/ecosoft/frappe-bench/apps/frappe/frappe/model/base_document.py", line 67, in get_controller
    return import_controller(doctype)
  File "/home/ecosoft/frappe-bench/apps/frappe/frappe/model/base_document.py", line 91, in import_controller
    module = load_doctype_module(doctype, module_name)
  File "/home/ecosoft/frappe-bench/apps/frappe/frappe/modules/utils.py", line 247, in load_doctype_module
    app = get_module_app(module)
  File "/home/ecosoft/frappe-bench/apps/frappe/frappe/modules/utils.py", line 270, in get_module_app
    app = frappe.local.module_app.get(scrub(module))
AttributeError: 'NoneType' object has no attribute 'get'
2024-09-10 21:31:08,447 ERROR frappe Could not take error snapshot: 'NoneType' object has no attribute 'get'
Site: dcode.com
Form Dict: {}
Traceback (most recent call last):
  File "/home/ecosoft/frappe-bench/apps/frappe/frappe/app.py", line 99, in application
    init_request(request)
  File "/home/ecosoft/frappe-bench/apps/frappe/frappe/app.py", line 172, in init_request
    frappe.init(site=site, sites_path=_sites_path, force=True)
  File "/home/ecosoft/frappe-bench/apps/frappe/frappe/__init__.py", line 312, in init
    setup_module_map(include_all_apps=not (frappe.request or frappe.job or frappe.flags.in_migrate))
  File "/home/ecosoft/frappe-bench/apps/frappe/frappe/__init__.py", line 1746, in setup_module_map
    for module in get_module_list(app):
  File "/home/ecosoft/frappe-bench/apps/frappe/frappe/__init__.py", line 1594, in get_module_list
    return get_file_items(get_app_path(app_name, "modules.txt"))
  File "/home/ecosoft/frappe-bench/apps/frappe/frappe/__init__.py", line 1559, in get_app_path
    return get_pymodule_path(app_name, *joins)
  File "/home/ecosoft/frappe-bench/apps/frappe/frappe/__init__.py", line 1589, in get_pymodule_path
    return abspath(join(dirname(get_module(scrub(modulename)).__file__ or ""), *joins))
  File "/home/ecosoft/frappe-bench/apps/frappe/frappe/__init__.py", line 1530, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'erpnext'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ecosoft/frappe-bench/apps/frappe/frappe/utils/error.py", line 87, in log_error_snapshot
    log_error(title=str(exception), defer_insert=True)
  File "/home/ecosoft/frappe-bench/apps/frappe/frappe/utils/error.py", line 62, in log_error
    error_log = frappe.get_doc(
  File "/home/ecosoft/frappe-bench/apps/frappe/frappe/__init__.py", line 1387, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/ecosoft/frappe-bench/apps/frappe/frappe/model/document.py", line 85, in get_doc
    controller = get_controller(doctype)
  File "/home/ecosoft/frappe-bench/apps/frappe/frappe/model/base_document.py", line 67, in get_controller
    return import_controller(doctype)
  File "/home/ecosoft/frappe-bench/apps/frappe/frappe/model/base_document.py", line 91, in import_controller
    module = load_doctype_module(doctype, module_name)
  File "/home/ecosoft/frappe-bench/apps/frappe/frappe/modules/utils.py", line 247, in load_doctype_module
    app = get_module_app(module)
  File "/home/ecosoft/frappe-bench/apps/frappe/frappe/modules/utils.py", line 270, in get_module_app
    app = frappe.local.module_app.get(scrub(module))
AttributeError: 'NoneType' object has no attribute 'get'
2024-09-10 21:31:08,616 ERROR frappe Could not take error snapshot: 'NoneType' object has no attribute 'get'
Site: dcode.com
Form Dict: {}
Traceback (most recent call last):
  File "/home/ecosoft/frappe-bench/apps/frappe/frappe/app.py", line 99, in application
    init_request(request)
  File "/home/ecosoft/frappe-bench/apps/frappe/frappe/app.py", line 172, in init_request
    frappe.init(site=site, sites_path=_sites_path, force=True)
  File "/home/ecosoft/frappe-bench/apps/frappe/frappe/__init__.py", line 312, in init
    setup_module_map(include_all_apps=not (frappe.request or frappe.job or frappe.flags.in_migrate))
  File "/home/ecosoft/frappe-bench/apps/frappe/frappe/__init__.py", line 1746, in setup_module_map
    for module in get_module_list(app):
  File "/home/ecosoft/frappe-bench/apps/frappe/frappe/__init__.py", line 1594, in get_module_list
    return get_file_items(get_app_path(app_name, "modules.txt"))
  File "/home/ecosoft/frappe-bench/apps/frappe/frappe/__init__.py", line 1559, in get_app_path
    return get_pymodule_path(app_name, *joins)
  File "/home/ecosoft/frappe-bench/apps/frappe/frappe/__init__.py", line 1589, in get_pymodule_path
    return abspath(join(dirname(get_module(scrub(modulename)).__file__ or ""), *joins))
  File "/home/ecosoft/frappe-bench/apps/frappe/frappe/__init__.py", line 1530, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'erpnext'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ecosoft/frappe-bench/apps/frappe/frappe/utils/error.py", line 87, in log_error_snapshot
    log_error(title=str(exception), defer_insert=True)
  File "/home/ecosoft/frappe-bench/apps/frappe/frappe/utils/error.py", line 62, in log_error
    error_log = frappe.get_doc(
  File "/home/ecosoft/frappe-bench/apps/frappe/frappe/__init__.py", line 1387, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/ecosoft/frappe-bench/apps/frappe/frappe/model/document.py", line 85, in get_doc
    controller = get_controller(doctype)
  File "/home/ecosoft/frappe-bench/apps/frappe/frappe/model/base_document.py", line 67, in get_controller
    return import_controller(doctype)
  File "/home/ecosoft/frappe-bench/apps/frappe/frappe/model/base_document.py", line 91, in import_controller
    module = load_doctype_module(doctype, module_name)
  File "/home/ecosoft/frappe-bench/apps/frappe/frappe/modules/utils.py", line 247, in load_doctype_module
    app = get_module_app(module)
  File "/home/ecosoft/frappe-bench/apps/frappe/frappe/modules/utils.py", line 270, in get_module_app
    app = frappe.local.module_app.get(scrub(module))
AttributeError: 'NoneType' object has no attribute 'get'
2024-09-10 21:31:08,856 ERROR frappe Could not take error snapshot: 'NoneType' object has no attribute 'get'
Site: dcode.com
Form Dict: {}
Traceback (most recent call last):
  File "/home/ecosoft/frappe-bench/apps/frappe/frappe/app.py", line 99, in application
    init_request(request)
  File "/home/ecosoft/frappe-bench/apps/frappe/frappe/app.py", line 172, in init_request
    frappe.init(site=site, sites_path=_sites_path, force=True)
  File "/home/ecosoft/frappe-bench/apps/frappe/frappe/__init__.py", line 312, in init
    setup_module_map(include_all_apps=not (frappe.request or frappe.job or frappe.flags.in_migrate))
  File "/home/ecosoft/frappe-bench/apps/frappe/frappe/__init__.py", line 1746, in setup_module_map
    for module in get_module_list(app):
  File "/home/ecosoft/frappe-bench/apps/frappe/frappe/__init__.py", line 1594, in get_module_list
    return get_file_items(get_app_path(app_name, "modules.txt"))
  File "/home/ecosoft/frappe-bench/apps/frappe/frappe/__init__.py", line 1559, in get_app_path
    return get_pymodule_path(app_name, *joins)
  File "/home/ecosoft/frappe-bench/apps/frappe/frappe/__init__.py", line 1589, in get_pymodule_path
    return abspath(join(dirname(get_module(scrub(modulename)).__file__ or ""), *joins))
  File "/home/ecosoft/frappe-bench/apps/frappe/frappe/__init__.py", line 1530, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'erpnext'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ecosoft/frappe-bench/apps/frappe/frappe/utils/error.py", line 87, in log_error_snapshot
    log_error(title=str(exception), defer_insert=True)
  File "/home/ecosoft/frappe-bench/apps/frappe/frappe/utils/error.py", line 62, in log_error
    error_log = frappe.get_doc(
  File "/home/ecosoft/frappe-bench/apps/frappe/frappe/__init__.py", line 1387, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/ecosoft/frappe-bench/apps/frappe/frappe/model/document.py", line 85, in get_doc
    controller = get_controller(doctype)
  File "/home/ecosoft/frappe-bench/apps/frappe/frappe/model/base_document.py", line 67, in get_controller
    return import_controller(doctype)
  File "/home/ecosoft/frappe-bench/apps/frappe/frappe/model/base_document.py", line 91, in import_controller
    module = load_doctype_module(doctype, module_name)
  File "/home/ecosoft/frappe-bench/apps/frappe/frappe/modules/utils.py", line 247, in load_doctype_module
    app = get_module_app(module)
  File "/home/ecosoft/frappe-bench/apps/frappe/frappe/modules/utils.py", line 270, in get_module_app
    app = frappe.local.module_app.get(scrub(module))
AttributeError: 'NoneType' object has no attribute 'get'
